// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package store

import (
	"context"
)

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (name, message) VALUES (?, ?)
`

type CreateEntryParams struct {
	Name    string
	Message string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.ExecContext(ctx, createEntry, arg.Name, arg.Message)
	return err
}

const listEntries = `-- name: ListEntries :many
SELECT id, name, message, created_at FROM entries ORDER BY created_at DESC, id DESC
`

// Newest first. CURRENT_TIMESTAMP only resolves to the second, so entries
// signed within the same second tie; id breaks the tie in insertion order.
func (q *Queries) ListEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
