// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Entry struct {
	ID        int64
	Name      string
	Message   string
	CreatedAt sql.NullTime
}
